// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwghpkijwhhkqfcibyyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3Z2hwa2lqd2hoa3FmY2lieXlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAwMzY3MDcsImV4cCI6MjA0NTYxMjcwN30.B87EFsSjjSzpVKPuf6AsJcgNxuVBzxQICt_jQjBx8oM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);